name: Ambassador
main: com.magicalpoof.ambassador.Main
version: 1.0
api-version: 1.19
commands:
    ambaset:
        description: Установить амбассадора сервера.
    ambarem:
        description: Убрать амбассадора сервера.